---
- name: Ensure required vars for the geerlingguy.certbot role are defined
  assert:
    that:
      - certbot_auto_renew_options is defined
      - certbot_create_standalone_stop_services is defined

- import_role:
    name: geerlingguy.certbot
  vars:
    certbot_auto_renew: true
    certbot_auto_renew_user: root
    certbot_admin_email: "{{ letsencrypt_admin_email }}"
    certbot_create_if_missing: yes
    certbot_certs:
      - domains: "{{ letsencrypt_domains }}"

# prefer the cron job installed above by the geerlingguy.certbot role, over
# which we have more control (through the `certbot_auto_renew_options` var)
- name: remove renewal job installed by certbot apt package
  file:
    path: /etc/cron.d/certbot
    state: absent

- name: update logrotation script provided by certbot apt package
  template:
    src: certbot-logrotate.j2
    dest: /etc/logrotate.d/certbot
    mode: 0644
