- import_role:
    name: geerlingguy.certbot
  vars:
    certbot_auto_renew_user: root
    certbot_admin_email: "{{ letsencrypt_admin_email }}"
    certbot_create_if_missing: yes
    certbot_certs:
      - domains: "{{ letsencrypt_domains }}"
    certbot_auto_renew_options: "--quiet --no-self-upgrade --pre-hook 'systemctl stop nginx' --post-hook 'systemctl start nginx'"

- name: set logrotation
  template:
    src: letsencrypt-logrotate.j2
    dest: /etc/logrotate.d/letsencrypt
    mode: 0644
