---
- import_role:
    name: geerlingguy.certbot
  vars:
    certbot_auto_renew: true
    certbot_auto_renew_user: root
    certbot_create_standalone_stop_services: "{{ letsencrypt_create_standalone_stop_services }}"
    certbot_create_command: >-
      {{ certbot_script }} certonly
      {{ '--test-cert' if letsencrypt_use_test_cert else '' }}
      --standalone --noninteractive --agree-tos
      --email {{ cert_item.email | default(certbot_admin_email) }}
      --cert-name {{ cert_item.domains | first }}
      -d {{ cert_item.domains | join(',') }}
    certbot_auto_renew_options: "{{ letsencrypt_auto_renew_options }}"
    certbot_auto_renew_hour: "{{ letsencrypt_auto_renew_hour }}"
    certbot_admin_email: "{{ letsencrypt_admin_email }}"
    certbot_create_if_missing: yes
    certbot_certs:
      - domains: "{{ letsencrypt_domains }}"

# prefer the cron job installed above by the geerlingguy.certbot role, over
# which we have more control (through the `certbot_auto_renew_options` var)
- name: remove renewal job installed by certbot apt package
  file:
    path: /etc/cron.d/certbot
    state: absent

- name: remove logrotation script provided by certbot apt package
  file:
    path: /etc/logrotate.d/certbot
    state: absent

# built in letsencrypt log management is not very functional (eg
# http://www.sweetapplepress.com/healthcareguide.html) , so just use our own
- name: install letsencrypt log cleanup script
  template:
    src: letsencrypt_log_cleanup.j2
    dest: /etc/cron.daily/letsencrypt_log_cleanup
    mode: 0744
